version: '3.9'
services:
  mongo:
    image: mongo
    ports:
      - $MONGO_LOCAL_PORT:$MONGO_DOCKER_PORT
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_USERNAME
      MONGO_INITDB_DATABASE: restful-auth
  main:
    build:
      context: .
    ports:
      - $SERVER_PORT:$SERVER_PORT
    depends_on:
      - mongo
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json