version: '3.9'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: restful-auth
  main:
    build: 
      context: .
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json